In [2]:
# Base code from stack exchange https://stackoverflow.com/questions/78088764/finding-the-coefficient-a-of-a-linear-equation-of-the-form-y-ax
# Formed the class and training loop for me, I inputted data and edited code to remove errors

import torch
from torch.optim import Adam
import numpy as np
import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using Device: {device}")

class FindParameter(torch.nn.Module):
    def __init__(self):
        super(FindParameter, self).__init__()
        self.a = torch.nn.Parameter(data=torch.tensor([1.0], dtype=torch.float32, requires_grad=True))

    def forward(self, input):
        return self.a * input


a = 3.5
X = torch.randint(1, 10, (10,), dtype=torch.float32).to(device)
Y = a * X

print(f"{X = }")
print(f"{Y = }")

model = FindParameter().to(device)
loss_f = torch.nn.MSELoss()
optimizer = Adam(model.parameters(), lr=1e-2)

epochs = 1000

for epoch in range(epochs):
    optimizer.zero_grad()
    y_pred = model(X)

    loss = loss_f(y_pred, Y)
    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}, a: {model.a.item()}")

print(loss.item())
print(model.a.item())

Using Device: cuda
X = tensor([7., 6., 2., 7., 8., 3., 4., 7., 8., 4.], device='cuda:0')
Y = tensor([24.5000, 21.0000,  7.0000, 24.5000, 28.0000, 10.5000, 14.0000, 24.5000,
        28.0000, 14.0000], device='cuda:0')
Epoch 0, Loss: 222.5, a: 1.0099999904632568
Epoch 100, Loss: 88.47396850585938, a: 1.9316694736480713
Epoch 200, Loss: 27.902484893798828, a: 2.620351791381836
Epoch 300, Loss: 6.730287075042725, a: 3.0685925483703613
Epoch 400, Loss: 1.21005117893219, a: 3.317350387573242
Epoch 500, Loss: 0.1603485345840454, a: 3.4336135387420654
Epoch 600, Loss: 0.015569335781037807, a: 3.47934627532959
Epoch 700, Loss: 0.0010994423646479845, a: 3.494520425796509
Epoch 800, Loss: 5.5757085647201166e-05, a: 3.4987680912017822
Epoch 900, Loss: 2.0039831269969e-06, a: 3.4997668266296387
5.252034185332377e-08
3.499962329864502


In [2]:
list(model.parameters())

[Parameter containing:
 tensor([3.5000], device='cuda:0', requires_grad=True)]

In [12]:
torch.randint(1, 10, (20,), dtype=torch.float32)

tensor([8., 2., 4., 6., 7., 1., 3., 7., 4., 7., 9., 1., 3., 5., 4., 4., 5., 7.,
        1., 3.])

In [20]:
class linear_test(torch.nn.Module):
    def __init__(self):
        super(linear_test,self).__init__()
        # Parameters
        self.m = torch.nn.Parameter(data=torch.tensor([1.0], dtype=torch.float32, requires_grad=True))
        self.c = torch.nn.Parameter(data=torch.tensor([1.0], dtype=torch.float32, requires_grad=True))

    def forward(self,input):
        return self.m * input + self.c

# Form training data
m = 10
c = 12
X = torch.randint(1, 10, (50,), dtype=torch.float32).to(device)
Y = m*X + c

print(f"{X = }")
print(f"{Y = }")

model = linear_test().to(device)
loss_f = torch.nn.MSELoss()
optimizer = Adam(model.parameters(), lr=1e-2)

epochs = 10000

for epoch in range(epochs):
    optimizer.zero_grad()
    y_pred = model(X)

    loss = loss_f(y_pred, Y)
    loss.backward()
    optimizer.step()

    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}, m: {model.m.item()}, c: {model.c.item()}")

print(f"Final Loss: {loss.item()}")
print(f"Final m: {model.m.item()}")
print(f"Final c: {model.c.item()}")

X = tensor([7., 7., 4., 2., 4., 3., 7., 9., 5., 7., 4., 1., 4., 2., 3., 6., 9., 3.,
        2., 3., 3., 4., 4., 1., 2., 5., 6., 4., 1., 9., 6., 7., 8., 4., 6., 4.,
        9., 4., 5., 5., 5., 4., 5., 4., 6., 5., 1., 5., 1., 7.],
       device='cuda:0')
Y = tensor([ 82.,  82.,  52.,  32.,  52.,  42.,  82., 102.,  62.,  82.,  52.,  22.,
         52.,  32.,  42.,  72., 102.,  42.,  32.,  42.,  42.,  52.,  52.,  22.,
         32.,  62.,  72.,  52.,  22., 102.,  72.,  82.,  92.,  52.,  72.,  52.,
        102.,  52.,  62.,  62.,  62.,  52.,  62.,  52.,  72.,  62.,  22.,  62.,
         22.,  82.], device='cuda:0')
Epoch 0, Loss: 3178.119873046875, m: 1.0099999904632568, c: 1.0099999904632568
Epoch 1000, Loss: 161.67578125, m: 8.211641311645508, c: 8.237807273864746
Epoch 2000, Loss: 0.9927195310592651, m: 10.163670539855957, c: 10.314260482788086
Epoch 3000, Loss: 0.3464347720146179, m: 10.247573852539062, c: 10.632641792297363
Epoch 4000, Loss: 0.21811223030090332, m: 10.196943283081055, c: 

In [23]:
class quadratic_test(torch.nn.Module):
    def __init__(self):
        super(quadratic_test,self).__init__()
        # Parameters
        self.a = torch.nn.Parameter(data=torch.tensor([1.0], dtype=torch.float32, requires_grad=True))
        self.b = torch.nn.Parameter(data=torch.tensor([1.0], dtype=torch.float32, requires_grad=True))
        self.c = torch.nn.Parameter(data=torch.tensor([1.0], dtype=torch.float32, requires_grad=True))

    def forward(self,input):
        return self.a*input**2 + self.b*input + self.c

# Form training data
a = 1
b = -4
c = 3
X = torch.randint(1, 10, (50,), dtype=torch.float32).to(device)
Y = a*X**2 + b*X + c

model = quadratic_test().to(device)
loss_f = torch.nn.MSELoss()
optimizer = Adam(model.parameters(), lr=1e-2)

epochs = 10000

for epoch in range(epochs):
    optimizer.zero_grad()
    y_pred = model(X)

    loss = loss_f(y_pred, Y)
    loss.backward()
    optimizer.step()

    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}, a: {model.a.item()}, b: {model.b.item()}, c: {model.c.item()}")

print(f"Final Loss: {loss.item()}")
print(f"Final a: {model.a.item()}")
print(f"Final b: {model.b.item()}")
print(f"Final c: {model.c.item()}")

Epoch 0, Loss: 735.7999877929688, a: 0.9900000095367432, b: 0.9900000095367432, c: 0.9900000095367432
Epoch 1000, Loss: 3.6948978900909424, a: 0.67720627784729, b: -0.7560951113700867, c: -2.3576982021331787
Epoch 2000, Loss: 1.733394742012024, a: 0.7702591419219971, b: -1.4239493608474731, c: -2.729172706604004
Epoch 3000, Loss: 1.1752963066101074, a: 0.8129366040229797, b: -1.890032172203064, c: -1.7541855573654175
Epoch 4000, Loss: 0.6107936501502991, a: 0.8652052283287048, b: -2.479386806488037, c: -0.42726579308509827
Epoch 5000, Loss: 0.20618192851543427, a: 0.921726644039154, b: -3.1168816089630127, c: 1.0089696645736694
Epoch 6000, Loss: 0.034272484481334686, a: 0.9681078195571899, b: -3.6401431560516357, c: 2.1885225772857666
Epoch 7000, Loss: 0.0017528521129861474, a: 0.9927934408187866, b: -3.9186818599700928, c: 2.816615581512451
Epoch 8000, Loss: 1.239864832314197e-05, a: 0.9993945956230164, b: -3.993169069290161, c: 2.9845948219299316
Epoch 9000, Loss: 3.1425395619066876e

In [30]:
# Making a loss function
m1 = torch.tensor([[1+1j,2,3],[4,5-2j,6],[7,8+7j,9]])
m2 = torch.tensor([[9,8,7],[6,5,4],[3,2,1]])
m3 = torch.tensor([[1,6,3],[4,5,4],[2,8,9]])
print(f"Diff first: {(m3-m1).abs().square().sum().item()}")
print(f"Square first: {(m1.abs().square()-m3.abs().square()).sum().item()}")

Diff first: 99.0
Square first: 87.00000762939453


In [33]:
def mseloss(output, target):
    return (output-target).abs().square().sum()

In [31]:
import torch
import torch.nn as nn
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
loss = nn.L1Loss()
output = loss(input, target)
output.backward()
print("input: ", input)
print("target: ", target)
print("output: ", output)

input:  tensor([[-1.1409, -2.0849,  1.7829, -1.3735,  0.2510],
        [ 0.8853,  0.9318, -1.3917,  0.1950, -0.2102],
        [-0.2180,  0.0764,  2.3478, -0.1737,  2.4740]], requires_grad=True)
target:  tensor([[-0.5745,  1.6349,  0.7425, -0.9133,  1.3114],
        [ 0.9814,  0.3599,  0.1797, -0.0538, -0.3924],
        [-1.4799, -0.3878,  0.4494, -0.2599, -0.6376]])
output:  tensor(1.0893, grad_fn=<MeanBackward0>)


In [34]:
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = mseloss(input, target)
output.backward()
print("input: ", input)
print("target: ", target)
print("output: ", output)

input:  tensor([[ 0.6910,  0.8869,  0.8833, -0.2762, -1.0818],
        [-1.9304,  0.7685,  0.4189, -1.7208,  1.4043],
        [ 0.7033,  0.2609,  0.3491,  0.2938,  0.7813]], requires_grad=True)
target:  tensor([[ 0.9096, -0.9433, -0.6552, -0.7087, -0.5643],
        [-0.4877,  1.3950, -1.0782, -0.3741, -0.9440],
        [-0.7897, -0.7403,  1.0434,  0.1649,  0.9874]])
output:  tensor(22.0342, grad_fn=<SumBackward0>)


In [53]:
class matrix_test(nn.Module):
    def __init__(self):
        super(matrix_test,self).__init__()
        # Parameters
        self.a = torch.nn.Parameter(data=torch.tensor([1.0], dtype=torch.float32, requires_grad=True))

        self.m = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]).to(device)
    
    def forward(self, input_m):
        t = torch.exp(1j*self.a) * self.m
        return torch.matmul(t, input_m)
    

# Form training data
a = (torch.exp(1j*torch.tensor([5.0])) * torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype=torch.cfloat)).to(device)
X = torch.rand((3,1),dtype=torch.cfloat).to(device)
Y = torch.matmul(a, X)

model = matrix_test().to(device)
optimizer = Adam(model.parameters(), lr=1e-2)

epochs = 10000

for epoch in range(epochs):
    optimizer.zero_grad()
    y_pred = model(X)

    loss = mseloss(y_pred, Y)
    loss.backward()
    optimizer.step()

    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}, a: {model.a.item()}")

print(f"Final Loss: {loss.item()}")
print(f"Final a: {model.a.item()}")

Epoch 0, Loss: 1245.85546875, a: 0.9900000095367432
Epoch 1000, Loss: 5.226263866120462e-10, a: -1.2831841707229614
Epoch 2000, Loss: 3.3089350703896514e-10, a: -1.28318452835083
Epoch 3000, Loss: 7.59081686396712e-11, a: -1.2831848859786987
Epoch 4000, Loss: 1.375610736431554e-11, a: -1.2831851243972778
Epoch 5000, Loss: 1.375610736431554e-11, a: -1.2831851243972778
Epoch 6000, Loss: 7.819522807039903e-12, a: -1.2831852436065674
Epoch 7000, Loss: 7.819522807039903e-12, a: -1.2831852436065674
Epoch 8000, Loss: 4.806821607417078e-12, a: -1.283185362815857
Epoch 9000, Loss: 4.806821607417078e-12, a: -1.283185362815857
Final Loss: 7.819522807039903e-12
Final a: -1.2831852436065674


In [35]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
b = torch.tensor([[1],[2],[3]])

torch.matmul(a,b)

tensor([[14],
        [32],
        [50]])

In [50]:
torch.exp(1j*torch.tensor([5.0]))

tensor([0.2837-0.9589j])